### PR TITLE
Added some very basic indentation support for blade syntax

### PR DESCRIPTION
**Pull request by mxaddict**
Added VERY VERY Basic indent support, that works for HTML + PHP syntax inside of blade files and somewhat for the blade syntax

### CODE REVIEW

**Comment by mxaddict** [comment]
No bights?

**Comment by xsbeats** [comment]
I will be honest and say the reason I have not contributed or merged anything recently is because I haven't found a fullproof way of testing changes.

**Comment by mxaddict** [comment]
I was actually going to ask how you tested updates, I'm pretty new to vimscript and I'm kinda spoiled by the testing tool sets for other projects, I'm still looking around at some other VIM plugins to try and learn how they do testing.

Let me know if you find a solid solution and I will implement some tests or atleast try to help out :+1:

**Comment by friparia** [comment]
:+1:

**Pull request merged**
